# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    huggingface_token: ''
    flouci_mode_test: 'true'
    flouci_public_key: ''
    flouci_private_key: ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ActivityEmailService:
        arguments:
            $mailerFrom: '%env(MAILER_FROM)%'

    App\Controller\AiController:
        arguments:
            $huggingFaceToken: '%env(default:huggingface_token:HUGGINGFACE_TOKEN)%'

    App\Service\FlouciService:
        arguments:
            $publicKey:  '%env(default:flouci_public_key:FLOUCI_PUBLIC_KEY)%'
            $privateKey: '%env(default:flouci_private_key:FLOUCI_PRIVATE_KEY)%'
            $modeTest:   '%env(default:flouci_mode_test:FLOUCI_MODE_TEST)%'
