parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\AIService:
        arguments:
            $huggingfaceApiKey: '%env(HUGGINGFACE_API_KEY)%'

    App\Service\FaceRecognitionService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\FingerprintBridgeService:
        arguments:
            $bridgeUrl: '%env(FINGERPRINT_BRIDGE_URL)%'
