parameters:
    huggingface_token: ''
    flouci_mode_test: 'true'
    flouci_public_key: ''
    flouci_private_key: ''
    app.weather.api_key: '%env(OPENWEATHER_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $openWeatherApiKey: '%env(OPENWEATHER_API_KEY)%'
            $geminiApiKey: '%env(GEMINI_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ActivityEmailService:
        arguments:
            $mailerFrom: '%env(MAILER_FROM)%'

    App\Controller\AiController:
        arguments:
            $huggingFaceToken: '%env(default:huggingface_token:HUGGINGFACE_TOKEN)%'

    App\Service\FlouciService:
        arguments:
            $publicKey:  '%env(default:flouci_public_key:FLOUCI_PUBLIC_KEY)%'
            $privateKey: '%env(default:flouci_private_key:FLOUCI_PRIVATE_KEY)%'
            $modeTest:   '%env(default:flouci_mode_test:FLOUCI_MODE_TEST)%'

    App\Service\AIService:
        arguments:
            $huggingfaceApiKey: '%env(HUGGINGFACE_API_KEY)%'

    App\Service\FaceRecognitionService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\FingerprintBridgeService:
        arguments:
            $bridgeUrl: '%env(FINGERPRINT_BRIDGE_URL)%'
